### ISSUE TITLE
Inaccurate results

### ISSUE THREAD

**Issue by DankMemeGuy** [d00ML0rDz/NsfwSpy.js#2]
I looked at the results section: https://github.com/NsfwSpy/NsfwSpy.js#results

In my testing of NSFWJS (Inception v3), it performs better than NSFWSpy in nearly all images I tested. Can you specify the images you used in your comparison testing, as well as which NSFWJS model you used? (Inception v3 vs MobileNet v2)

One example:
NSFWJS: https://i.imgur.com/tNJjWKF.png
NSFWSpy: https://i.imgur.com/0XP0WAl.png

Second example:
NSFWJS: https://i.imgur.com/TXCybfO.png
NSFWSpy: https://i.imgur.com/EBydbEL.png

The images are definitely not used in any of your or NSFWJS's training, so they are fresh images for the AI so there's no that it's biased based on that.

Second question: 

Can you specify what training data you used? Not every image, but what sources you used, for example, which subreddits, porn websites, categories, etc. I saw the listing of the files per classification, but I think specifying more granular data would be more useful, especially when retraining.

**Comment by d00ML0rDz** [comment]
Hey, thanks for creating this issue to ask for more information.

For our testing we used NSFWJS's Inception v3 model, which is their most accurate, you can see the small console application we use to help with our testing [here](https://github.com/NsfwSpy/NsfwSpy.js/tree/main/nsfwspy-performance-testing). We used 10,000 randomly selected images for each of the four categories, admittedly from our dataset, which of course could create a bias, but with our dataset being so large, that felt like a large assortment of images.

Regarding your examples, for the first image, NsfwSpy would consider that a 'pornography' image. Obviously it didn't classify it correctly, but it was closer than NSFWJS, although they may classify that image differently. For the second image, NsfwSpy was less confident, but did classify the image correctly, which is what we measure on the results section of our readme. How many images did you compare between the two libraries in your own testing? You can always use the application I mentioned above to quickly test a folder of images that are sorted into four folders for each of the categories.

To answer your second question, our image dataset comes from all over. Mostly reddit with us using a variety of different subreddits, but we don't have a definitive list of all of our sources. Wasn't that much organisation when we were putting it together unfortunately.

Hope that helps answer some of your questions :)

**Comment by DankMemeGuy** [comment]
thanks! great work btw :)
