### ISSUE TITLE
Incorrect model provided?

### ISSUE THREAD

**Issue by FitzM** [d00ML0rDz/NsfwSpy.js#4]
I'm trying to run this as a node.js module. I cloned your project, moved into the NsfwSpy-node directory and created my project. I load the model that is in `../models/mobilenet-v1.0.0/model.json` and I get the following error 

`This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.`

I don't think there is anything wrong with my code so far because it's just trying to run the example that you have in the Readme.md but my code is as follows 

```import { NsfwSpy } from '@nsfwspy/node';

const nsfwSpy = new NsfwSpy("../models/mobilenet-v1.0.0/model.json");

const filePath = "/home/fmx/Pictures/Screenshot_20230528_120040.png";
await nsfwSpy.load();
const result = await nsfwSpy.classifyImageFile(filePath);

console.log("Console Log!!")
console.log(result);```

**Comment by d00ML0rDz** [comment]
Hey, thanks for the issue.

From a quick Google, that doesn't sound like an error message, but more of a notification of how TensorFlow is running.

If you are seeing an exception being thrown, it may be because you're not specifying the NsfwSpy model is a file.

Try using the following and see if that works for you:

```
const nsfwSpy = new NsfwSpy("file://../models/mobilenet-v1.0.0/model.json");
```

**Comment by FitzM** [comment]
So Sorry! I was just coming in to delete my issue.  For some reason, and I still can't figure out why, my desktop wouldn't run the project but my laptop would, with the same exact project copied and pasted to the system. I really have no idea. I did change it to `"file://"` and it did resolve the issue.  I wasn't getting any other output so that info message was the only one I had to work with. 

On another note though, will video classification be supported in the .js package anytime soon? From what I found in the documentation it doesn't exist currently?

**Comment by d00ML0rDz** [comment]
If you are still getting an error occurring on your desktop, you could try wrapping the code in a try catch block and see if an error is thrown. Feel free to paste it here if it does.

Don't have much time at the moment, so unlikely video support will get added in the near future. From a quick Google, you might be able to use a library such as https://www.npmjs.com/package/ffmpeg-extract-frames which uses ffmpeg to extract the frames from a video. You could use that and then run the frames through NsfwSpy 😊 That's how we do video classification in NsfwSpy.NET.

Hope that helps!
